---
abstract: unknown
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.34, CPAN::Meta::Converter version 2.150010'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Data-UUID-LibUUID
no_index:
  directory:
    - t
    - inc
requires:
  MIME::Base64: '0'
  Sub::Exporter: '0'
  Test::More: '0'
  Test::use::ok: '0'
  asa: '0'
version: 0.06_01
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
